### ISSUE TITLE
I had a question about how this works

### ISSUE THREAD

**Issue by XulaPize** [cocahonka/comfy-whitelist#25]
I have a small local server and atm it's only premium allowed, I want to open the server to Offline Account (Cracked Account).
My question is after setting up the plugin do I have to add every player that wants to join manually? (Both premium and cracked account)
I was wondering if this plugin have an option to be set ,so only cracked accounts require to be added and the premium account can join without anything!
Is this even possible?

**Comment by cocahonka** [comment]
Hello, I didn't fully understand your question. If you want your server to work with offline accounts, you should check out the [server.properties](https://minecraft.fandom.com/wiki/Server.properties) file, specifically the `online-mode` field. By setting it to `false`, your server will be able to allow both premium accounts and offline accounts. 

As for the whitelist functionality, it currently works based on usernames, meaning that regardless of whether the account is premium or offline, if the username is not in the whitelist, the player will not be able to join.

Thank you for your interest, and I apologize for the delayed response!
